// One demo video per exercise, embedded in the app. Filled from search results;
// when a video is missing or can't be embedded, the app falls back to a YouTube search.

export interface DemoVideo { videoId: string; title: string; channel: string }

export const EXERCISE_VIDEOS: Record<string, DemoVideo> = {
  ab_wheel: { videoId: "nCh8VfWY5_g", title: "How to do AB WHEEL Rollouts the Right Way (3 Tips!)", channel: "Redefining Strength" },
  ankle_dorsiflexion: { videoId: "CRgmHELYh3A", title: "Knee to Wall Ankle Mobilization", channel: "YouTube" },
  arm_circles: { videoId: "P3dzI9opLGE", title: "Arm Circles Dynamic Warmup", channel: "YouTube" },
  back_extension: { videoId: "JzovzOGudfc", title: "How To Do Back Hyperextension Exercise Correctly", channel: "YouTube" },
  band_dislocate: { videoId: "riVxa9By-pM", title: "How To Do Band Dislocates / Pass-Throughs (Shoulder Mobility)", channel: "YouTube" },
  band_pull_apart: { videoId: "smSSXITNpCI", title: "How To Do Band Pull Aparts", channel: "Rogue Fitness" },
  barbell_curl: { videoId: "dDI8ClxRS04", title: "Barbell Curl - Biceps Exercise - Bodybuilding.com", channel: "Bodybuilding.com" },
  barbell_row: { videoId: "ML1L5ytxLMY", title: "Barbell Row \u2014 Form, Mistakes, and Variations", channel: "YouTube" },
  bench: { videoId: "4Y2ZdHCOXok", title: "How to PROPERLY Bench Press for Growth (5 Easy Steps)", channel: "Jeremy Ethier" },
  bird_dog: { videoId: "KA0ekfSePrQ", title: "How to do a Bird Dog Exercise", channel: "YouTube" },
  box_squat: { videoId: "1SgHKc5tImQ", title: "Gym Shorts (How To): The Box Squat", channel: "Barbell Logic" },
  bulgarian_split_squat: { videoId: "VPhhE6bBzZE", title: "How To Do Bulgarian Split Squats Correctly", channel: "YouTube" },
  cable_crunch: { videoId: "36HK6uPM_PQ", title: "Want Better Abs? Learn How to Cable Crunch Properly by Dr. Jim Stoppani", channel: "Jim Stoppani" },
  cable_lateral_raise: { videoId: "qitQHqNZbeM", title: "How to PROPERLY Cable Lateral Raise (TRY THIS!)", channel: "YouTube" },
  cable_row: { videoId: "zFNYrNSES34", title: "Proper Form - The Seated Cable Row", channel: "YouTube" },
  calf_raise: { videoId: "k8ipHzKeAkQ", title: "Exercises with an Athletic Trainer: Standing Calf Raises", channel: "Children's Hospital Colorado" },
  calf_stretch: { videoId: "4fwN8uiF7z8", title: "Stretch Your Calves Against The Wall (CORRECTLY)", channel: "YouTube" },
  cat_cow: { videoId: "KzM3QWeajwA", title: "Cat Cow Exercise - Kinetic Sports Rehab", channel: "Kinetic Sports Rehab" },
  chest_supported_row: { videoId: "ro2vfHfD0DQ", title: "How To Do A Chest Supported Dumbbell Row Correctly", channel: "YouTube" },
  chinup: { videoId: "qV7vOUcUfD4", title: "How To Do CHIN-UPS: Grip, Weighted Chin-Ups, Programming, & Fixing Common Errors", channel: "YouTube" },
  close_grip_bench: { videoId: "hWEpF7lFR9Q", title: "Close Grip Bench Press: Gym Shorts (How To)", channel: "Barbell Logic" },
  couch_stretch: { videoId: "VZaWm5WjcX4", title: "Couch Stretch: How to", channel: "YouTube" },
  cross_body_shoulder: { videoId: "uNmWSg705JA", title: "How To Do A Cross Body Shoulder Stretch", channel: "YouTube" },
  db_bench: { videoId: "sTYWWaunX8o", title: "Dumbbell Bench Press: How To (3 steps to proper form)", channel: "YouTube" },
  db_curl: { videoId: "tE21E4kzXJI", title: "Dumbbell Curls: The PROPER Way to Do Them", channel: "YouTube" },
  db_incline_press: { videoId: "hChjZQhX1Ls", title: "How To: Dumbbell Incline Press", channel: "YouTube" },
  db_rdl: { videoId: "KYIJdN2gBmQ", title: "Dumbbell Romanian Deadlift Tutorial", channel: "YouTube" },
  db_row: { videoId: "Qx2f4YwJAu4", title: "One Arm Dumbbell Row\u2014how to do it properly", channel: "YouTube" },
  db_shoulder_press: { videoId: "WKEl69bIGus", title: "How to Do the Seated Dumbbell Shoulder Press", channel: "YouTube" },
  dead_bug: { videoId: "bxn9FBrt4-A", title: "How to do a Dead Bug", channel: "NASM" },
  deadlift: { videoId: "wYREQkVtvEc", title: "How To Deadlift: Starting Strength 5 Step Deadlift", channel: "Alan Thrall (Untamed Strength)" },
  dips: { videoId: "U7HeutDqS_w", title: "How To Do Parallel Bar Dips", channel: "YouTube" },
  doorway_pec_stretch: { videoId: "069o76BafTk", title: "OMPT Specialists - Physical Therapy Practical Tips: Doorway Pec Stretch", channel: "OMPT Specialists" },
  eccentric_wrist_ext: { videoId: "xdEwDxcHwoY", title: "Eccentric Wrist Extension for Tennis Elbow (Lateral Epicondylitis)", channel: "YouTube" },
  eccentric_wrist_flex: { videoId: "fQl7Qao_92k", title: "Eccentric Wrist Flexion for Golfer's Elbow (Medial Epicondylitis)", channel: "YouTube" },
  external_rotation: { videoId: "_UvmPNGtlPM", title: "Shoulder External Rotation with Resistive Band - Ask Doctor Jo", channel: "AskDoctorJo" },
  face_pull: { videoId: "ljgqer1ZpXg", title: "STOP F*cking Up Face Pulls (PROPER FORM!)", channel: "YouTube" },
  floor_press: { videoId: "Izkam7-uklQ", title: "How to Do the Barbell Floor Press - Men's Health", channel: "Men's Health" },
  front_squat: { videoId: "feGKhZ7unUg", title: "Gym Shorts (How To): The Front Squat", channel: "Barbell Logic" },
  glute_bridge: { videoId: "wQQ6N5piDG0", title: "Glute Bridge: Proper Form to Work Glutes, Hamstrings, and Quads", channel: "YouTube" },
  goblet_squat: { videoId: "7-80HiXX1K8", title: "Goblet Squat [How To]", channel: "Le Sweat" },
  good_morning: { videoId: "BJ0G0d_iOdo", title: "The Good Morning: Gym Shorts (How To)", channel: "Barbell Logic" },
  hack_squat: { videoId: "-lAnEGH2blE", title: "How to Do the Hack Squat", channel: "YouTube" },
  hammer_curl: { videoId: "8_BFFLUDu5Q", title: "How to Hammer Curl with Proper Form", channel: "YouTube" },
  hamstring_stretch: { videoId: "LVY692zJK0A", title: "Standing Hamstring Stretch", channel: "YouTube" },
  hanging_leg_raise: { videoId: "JXztA3fLp50", title: "Hanging Leg Raise (Proper Form)", channel: "YouTube" },
  hip_90_90: { videoId: "HUZimFZJZWU", title: "How to Do the 90/90 Switch for Hip Mobility (Step-by-Step Tutorial)", channel: "YouTube" },
  hip_thrust: { videoId: "qFxTNOiQIAU", title: "HOW TO: Do Hip Thrusts - Best Exercise For Glutes w/ Bret Contreras", channel: "YouTube" },
  incline_bench: { videoId: "SrqOu55lrYU", title: "How To: Incline Barbell Bench Press", channel: "YouTube" },
  landmine_press: { videoId: "BQE4_5yTVf8", title: "Landmine Press 1/2 Kneeling: How To (3 steps to proper form)", channel: "YouTube" },
  lat_pulldown: { videoId: "CAwf7n6Luuc", title: "How To: Lat Pulldown", channel: "YouTube" },
  lat_stretch: { videoId: "Q4ALgRuM2f4", title: "Modified Lat Stretch", channel: "YouTube" },
  lateral_raise: { videoId: "1ovNfOjGN8Q", title: "Full ROM Dumbbell Lateral Raise (Proper Form)", channel: "YouTube" },
  leg_curl: { videoId: "SbSNUXPRkc8", title: "How To Do A Lying Leg Curl (Prone Leg Curl)", channel: "YouTube" },
  leg_extension: { videoId: "xAUvXdHu1sI", title: "How to do the LEG EXTENSION properly (in just 80 seconds)", channel: "YouTube" },
  leg_press: { videoId: "v_VGieF9Ccc", title: "Proper Leg Press Technique", channel: "YouTube" },
  leg_swings: { videoId: "difYoBtZi2s", title: "How To Do Leg Swings", channel: "YouTube" },
  machine_chest_press: { videoId: "B-zyH8OTlsg", title: "Machine Chest Press: How To", channel: "YouTube" },
  machine_shoulder_press: { videoId: "Gkk-6q7Rq-s", title: "How to Perform the Machine Shoulder Press", channel: "YouTube" },
  mcgill_curl_up: { videoId: "vLpHJ1Cxj6k", title: "McGill \"Big 3\" - The Curl-up", channel: "YouTube" },
  neutral_db_press: { videoId: "fZuQpjhaR_M", title: "How To Do A Neutral Grip Dumbbell Press", channel: "YouTube" },
  neutral_pulldown: { videoId: "E1FK9APxk54", title: "Neutral Grip Pulldowns [Perfect Form in 60 Seconds]", channel: "YouTube" },
  ohp: { videoId: "AhGW3XFG3M8", title: "Gym Shorts (How To): The Press", channel: "Barbell Logic" },
  overhead_triceps_ext: { videoId: "_iSX_125XUg", title: "Cable Tricep Extension Tutorial (Proper Form, Muscles Worked, Common Mistakes)", channel: "YouTube" },
  pallof_press: { videoId: "lqPrSGXfL1Q", title: "How To: Resistance Band Pallof Press", channel: "YouTube" },
  pigeon_stretch: { videoId: "op-eDU9eNqM", title: "Piriformis Pigeon Stretch - Ask Doctor Jo", channel: "AskDoctorJo" },
  plank: { videoId: "6LqqeBtFn9M", title: "How to do the perfect PLANK: technique and common mistakes", channel: "YouTube" },
  pullup: { videoId: "sIvJTfGxdFo", title: "The Official Pull-Up Checklist (AVOID MISTAKES!)", channel: "ATHLEAN-X" },
  push_press: { videoId: "a8HQo8z20Uo", title: "How to PUSH PRESS: How to perform the Barbell Push Press - exercise demo with proper technique", channel: "YouTube" },
  pushup: { videoId: "WDIpL0pjun0", title: "How to do a Push-Up", channel: "YouTube" },
  quad_stretch: { videoId: "kzAsm4WQqvQ", title: "How To Do A Standing Quad Stretch", channel: "YouTube" },
  rdl: { videoId: "_oyxCn2iSjU", title: "HOW TO DO ROMANIAN DEADLIFTS (RDLs): Build Beefy Hamstrings With Perfect Technique", channel: "YouTube" },
  rear_delt_fly: { videoId: "is-KyPOMqcY", title: "Bent Over Dumbbell Rear Delt Fly", channel: "YouTube" },
  rope_pushdown: { videoId: "K--j4Qh9d2s", title: "Cable Rope Triceps Pushdown - Proper Form", channel: "YouTube" },
  safety_bar_squat: { videoId: "CMn1Z9pzZAk", title: "Safety Squat Bar Squat (SSB Squat): How To (Gym Shorts)", channel: "Barbell Logic" },
  skull_crusher: { videoId: "ShR_FM3-wm4", title: "Skull Crusher - Proper Form & Technique", channel: "YouTube" },
  sleeper_stretch: { videoId: "9BN8bRVq3Xo", title: "Shoulder Sleeper Stretch for Internal Rotation Range of Motion - Ask Doctor Jo", channel: "AskDoctorJo" },
  spanish_squat: { videoId: "mik90mAS6fU", title: "Spanish Squats - Isometric Exercise for Patellar Tendinopathy", channel: "YouTube" },
  squat: { videoId: "jyopTyOjXb0", title: "Gym Shorts (How To): The Squat", channel: "Barbell Logic" },
  step_up: { videoId: "9ZknEYboBOQ", title: "Dumbbell Step-up - How To", channel: "YouTube" },
  straight_arm_pulldown: { videoId: "v-mqkbwFIrY", title: "Straight Arm Lat Pulldown (Proper Form)", channel: "YouTube" },
  sumo_deadlift: { videoId: "HBmLwb9IcaI", title: "Movement Demo - The Sumo Deadlift", channel: "YouTube" },
  thoracic_extension: { videoId: "J1-aNR1yby0", title: "Thoracic Extension on Foam Roller", channel: "YouTube" },
  trap_bar_deadlift: { videoId: "Vu4oXIRzx7w", title: "Trap Bar Deadlift: Gym Shorts (How To)", channel: "Barbell Logic" },
  triceps_pushdown: { videoId: "aUMD6SwvELU", title: "How To: Triceps Straight Bar Pushdown", channel: "YouTube" },
  triceps_stretch: { videoId: "o71LMT6ah48", title: "How to Do Overhead Triceps Stretch", channel: "YouTube" },
  walking_lunge: { videoId: "4XNQd5H0U0U", title: "Walking Lunge Form: How to Do It Correctly for Better Strength and Balance", channel: "YouTube" },
  worlds_greatest: { videoId: "-CiWQ2IvY34", title: "The World's Greatest Stretch (Mobility Exercise) by Squat University", channel: "Squat University" },
  wrist_extensor_stretch: { videoId: "80Y3HHMgo6w", title: "Wrist Extensor Stretch with Elbow Extension - Ask Doctor Jo", channel: "AskDoctorJo" },
  wrist_flexor_stretch: { videoId: "i-JV2PsFzWA", title: "Wrist Flexor Stretches with Elbow Extension - Ask Doctor Jo", channel: "AskDoctorJo" },
};
