/*
  # Skipping and the health profile

  1. Changes
    - sets.skipped / skip_reason: a set the user chose to skip (not a failed set)
    - workout_exercises.skipped / skip_reason: an exercise skipped entirely
  2. New tables
    - health_notes: the user's evolving health profile. Each row is one observation:
        kind = 'joint'    a sensitive joint (joint, severity 1–3)
             = 'avoid'    an exercise to avoid (exercise_id)
             = 'prefer'   an exercise that works well (exercise_id)
             = 'dislike'  an exercise the user doesn't enjoy (exercise_id)
             = 'note'     free-text context (e.g. "desk job, tight hips")
      source = where it came from: 'skip', 'coach' or 'user'.
      expires_at lets short-term issues (a tweak from one session) fade out.
  3. Security
    - RLS: users read and change only their own notes.
*/

ALTER TABLE sets ADD COLUMN IF NOT EXISTS skipped boolean NOT NULL DEFAULT false;
ALTER TABLE sets ADD COLUMN IF NOT EXISTS skip_reason text;
ALTER TABLE workout_exercises ADD COLUMN IF NOT EXISTS skipped boolean NOT NULL DEFAULT false;
ALTER TABLE workout_exercises ADD COLUMN IF NOT EXISTS skip_reason text;

CREATE TABLE IF NOT EXISTS health_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('joint', 'avoid', 'prefer', 'dislike', 'note')),
  joint text CHECK (joint IS NULL OR joint IN ('elbow', 'shoulder', 'wrist', 'knee', 'lowBack', 'hip')),
  exercise_id text,
  severity int NOT NULL DEFAULT 1 CHECK (severity BETWEEN 1 AND 3),
  note text NOT NULL DEFAULT '',
  source text NOT NULL DEFAULT 'user' CHECK (source IN ('skip', 'coach', 'user')),
  workout_id bigint REFERENCES workouts(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz
);
CREATE INDEX IF NOT EXISTS health_notes_user ON health_notes (user_id, created_at DESC);

ALTER TABLE health_notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read own rows" ON health_notes;
DROP POLICY IF EXISTS "Users insert own rows" ON health_notes;
DROP POLICY IF EXISTS "Users update own rows" ON health_notes;
DROP POLICY IF EXISTS "Users delete own rows" ON health_notes;
CREATE POLICY "Users read own rows" ON health_notes FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "Users insert own rows" ON health_notes FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users update own rows" ON health_notes FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users delete own rows" ON health_notes FOR DELETE TO authenticated USING (user_id = auth.uid());

GRANT SELECT, INSERT, UPDATE, DELETE ON health_notes TO authenticated;
