/*
  # Lighthouse schema

  Every table carries a user_id that defaults to the signed-in user, and row level
  security restricts each user to their own rows.

  1. Tables
    - profiles: training profile, one per user (created automatically on sign-up)
    - programs: the user's generated program (JSON), next day in the rotation, 5RM estimates
    - lift_states: progression state per exercise and tier (weight, stage, rep targets…)
    - workouts, workout_exercises, sets: logged sessions
    - coach_messages: AI coach conversation (written by the `coach` edge function)
    - bodyweights: bodyweight log
  2. Views
    - done_sets: every completed working/warm-up set of a finished workout (security invoker)
  3. Functions
    - convert_units(factor): rescales the caller's logged weights when they switch kg/lb
*/

-- ---------------------------------------------------------------------------
-- Tables

CREATE TABLE IF NOT EXISTS profiles (
  user_id uuid PRIMARY KEY DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  units text NOT NULL DEFAULT 'kg' CHECK (units IN ('kg', 'lb')),
  experience text NOT NULL DEFAULT 'beginner' CHECK (experience IN ('beginner', 'intermediate', 'advanced')),
  goal text NOT NULL DEFAULT 'strength' CHECK (goal IN ('strength', 'hypertrophy', 'general')),
  days_per_week int NOT NULL DEFAULT 4,
  session_minutes int NOT NULL DEFAULT 60,
  equipment jsonb NOT NULL DEFAULT '[]',
  limitations jsonb NOT NULL DEFAULT '[]',
  limitation_notes text NOT NULL DEFAULT '',
  bodyweight double precision,
  onboarded boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS programs (
  user_id uuid PRIMARY KEY DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  data jsonb NOT NULL,
  next_day int NOT NULL DEFAULT 0,
  five_rms jsonb NOT NULL DEFAULT '{}',
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lift_states (
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  exercise_id text NOT NULL,
  tier text NOT NULL,
  data jsonb NOT NULL,
  PRIMARY KEY (user_id, exercise_id, tier)
);

CREATE TABLE IF NOT EXISTS workouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  date date NOT NULL,
  day_index int,
  title text NOT NULL,
  status text NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'completed')),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  notes text NOT NULL DEFAULT '',
  summary jsonb
);
CREATE INDEX IF NOT EXISTS workouts_user_date ON workouts (user_id, date DESC);

CREATE TABLE IF NOT EXISTS workout_exercises (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  workout_id bigint NOT NULL REFERENCES workouts(id) ON DELETE CASCADE,
  exercise_id text NOT NULL,
  position int NOT NULL,
  tier text NOT NULL,
  slot_id text,
  scheme_label text NOT NULL DEFAULT '',
  rest_seconds int NOT NULL DEFAULT 90,
  notes text NOT NULL DEFAULT '',
  engine_note text,
  substituted_from text
);
CREATE INDEX IF NOT EXISTS wex_workout ON workout_exercises (workout_id);
CREATE INDEX IF NOT EXISTS wex_user_exercise ON workout_exercises (user_id, exercise_id);

CREATE TABLE IF NOT EXISTS sets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  workout_exercise_id bigint NOT NULL REFERENCES workout_exercises(id) ON DELETE CASCADE,
  position int NOT NULL,
  kind text NOT NULL DEFAULT 'working' CHECK (kind IN ('warmup', 'working')),
  target_reps int,
  target_weight double precision,
  amrap boolean NOT NULL DEFAULT false,
  actual_reps int,
  actual_weight double precision,
  rpe double precision,
  done boolean NOT NULL DEFAULT false,
  completed_at timestamptz
);
CREATE INDEX IF NOT EXISTS sets_wex ON sets (workout_exercise_id);

CREATE TABLE IF NOT EXISTS coach_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  workout_id bigint REFERENCES workouts(id) ON DELETE SET NULL,
  role text NOT NULL CHECK (role IN ('user', 'assistant')),
  content text NOT NULL,
  actions jsonb NOT NULL DEFAULT '[]',
  sources jsonb NOT NULL DEFAULT '[]',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS coach_user_workout ON coach_messages (user_id, workout_id);

CREATE TABLE IF NOT EXISTS bodyweights (
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  date date NOT NULL,
  weight double precision NOT NULL,
  PRIMARY KEY (user_id, date)
);

-- ---------------------------------------------------------------------------
-- Row level security: each user sees and changes only their own rows.

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE lift_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE coach_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE bodyweights ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['profiles', 'programs', 'lift_states', 'workouts', 'workout_exercises', 'sets', 'coach_messages', 'bodyweights']
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Users read own rows" ON %I', t);
    EXECUTE format('DROP POLICY IF EXISTS "Users insert own rows" ON %I', t);
    EXECUTE format('DROP POLICY IF EXISTS "Users update own rows" ON %I', t);
    EXECUTE format('DROP POLICY IF EXISTS "Users delete own rows" ON %I', t);
    EXECUTE format('CREATE POLICY "Users read own rows" ON %I FOR SELECT TO authenticated USING (user_id = auth.uid())', t);
    EXECUTE format('CREATE POLICY "Users insert own rows" ON %I FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid())', t);
    EXECUTE format('CREATE POLICY "Users update own rows" ON %I FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid())', t);
    EXECUTE format('CREATE POLICY "Users delete own rows" ON %I FOR DELETE TO authenticated USING (user_id = auth.uid())', t);
  END LOOP;
END $$;

-- Child rows must belong to a parent the user owns.
CREATE OR REPLACE FUNCTION check_parent_owner() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
BEGIN
  IF TG_TABLE_NAME = 'workout_exercises' THEN
    IF NOT EXISTS (SELECT 1 FROM workouts WHERE id = NEW.workout_id AND user_id = NEW.user_id) THEN
      RAISE EXCEPTION 'workout not found';
    END IF;
  ELSIF TG_TABLE_NAME = 'sets' THEN
    IF NOT EXISTS (SELECT 1 FROM workout_exercises WHERE id = NEW.workout_exercise_id AND user_id = NEW.user_id) THEN
      RAISE EXCEPTION 'exercise not found';
    END IF;
  ELSIF TG_TABLE_NAME = 'coach_messages' AND NEW.workout_id IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM workouts WHERE id = NEW.workout_id AND user_id = NEW.user_id) THEN
      RAISE EXCEPTION 'workout not found';
    END IF;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS wex_parent_owner ON workout_exercises;
CREATE TRIGGER wex_parent_owner BEFORE INSERT OR UPDATE OF workout_id, user_id ON workout_exercises
  FOR EACH ROW EXECUTE FUNCTION check_parent_owner();
DROP TRIGGER IF EXISTS sets_parent_owner ON sets;
CREATE TRIGGER sets_parent_owner BEFORE INSERT OR UPDATE OF workout_exercise_id, user_id ON sets
  FOR EACH ROW EXECUTE FUNCTION check_parent_owner();
DROP TRIGGER IF EXISTS coach_parent_owner ON coach_messages;
CREATE TRIGGER coach_parent_owner BEFORE INSERT OR UPDATE OF workout_id, user_id ON coach_messages
  FOR EACH ROW EXECUTE FUNCTION check_parent_owner();

-- ---------------------------------------------------------------------------
-- Profile row for every new account

CREATE OR REPLACE FUNCTION handle_new_user() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (user_id, name)
  VALUES (NEW.id, COALESCE(NULLIF(NEW.raw_user_meta_data ->> 'name', ''), split_part(NEW.email, '@', 1)))
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ---------------------------------------------------------------------------
-- Completed sets, flattened for history, stats and "previous performance".

CREATE OR REPLACE VIEW done_sets WITH (security_invoker = true) AS
SELECT
  s.id AS set_id,
  w.user_id,
  w.id AS workout_id,
  w.date,
  w.title,
  we.id AS workout_exercise_id,
  we.exercise_id,
  we.tier,
  we.position AS exercise_position,
  we.notes AS exercise_notes,
  s.position,
  s.kind,
  s.actual_weight,
  s.actual_reps,
  s.rpe
FROM sets s
JOIN workout_exercises we ON we.id = s.workout_exercise_id
JOIN workouts w ON w.id = we.workout_id
WHERE s.done AND w.status = 'completed';

GRANT SELECT ON done_sets TO authenticated;

-- ---------------------------------------------------------------------------
-- Unit switch: rescale every logged weight for the calling user.

CREATE OR REPLACE FUNCTION convert_units(factor double precision) RETURNS void
LANGUAGE sql SECURITY INVOKER SET search_path = public AS $$
  UPDATE sets SET
    target_weight = round((target_weight * factor)::numeric, 1),
    actual_weight = round((actual_weight * factor)::numeric, 1)
  WHERE user_id = auth.uid();
  UPDATE bodyweights SET weight = round((weight * factor)::numeric, 1) WHERE user_id = auth.uid();
  UPDATE profiles SET bodyweight = round((bodyweight * factor)::numeric, 1) WHERE user_id = auth.uid();
$$;

GRANT EXECUTE ON FUNCTION convert_units(double precision) TO authenticated;